version: "3.8"
services:

  mysql:
    build: ./docker/mysql
    container_name: "${APP_SLUG}_mysql"
    image: trackstar_mysql:1.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/database:/var/lib/mysql:cached
      - ./docker/mysql/config:/etc/mysql/mysql.conf.d:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"


  webapp:
    build: ./docker/nginx
    image: trackstar_nginx:1.0
    container_name: "${APP_SLUG}_nginx"
    links:
      - php-fpm:php-fpm
    volumes:
      - ./application:/var/www:cached
      - ./docker/nginx/logs:/var/log/nginx:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"


  php-fpm:
    build: ./docker/php-fpm/local
    image: trackstar_php-fpm:1.4
    container_name: "${APP_SLUG}_php-fpm"
    links:
      - mysql:mysql
    volumes:
      - ./application:/var/www:cached
    environment:
      APP_SLUG: ${APP_SLUG}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: "${APP_SLUG}_mysql"
      DB_PORT: ${MYSQL_PORT}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      APP_NAME: ${APP_SLUG}
      APP_DEBUG: '${APP_DEBUG}'
      APP_ENV: ${APP_ENV}
